version: "3"
services:
  telegram-lawn-bot:
    build: .
    environment: 
      - "RUST_BACKTRACE=1"
      - "http_proxy=http://localhost:7890"
      - "https_proxy=http://localhost:7890"
      - "all_proxy=socks5://localhost:7890"
    network_mode: host
    restart: unless-stopped